Use URLField for personal website
IMGIITRoorkee/omniport-service-common-biodata pull request #2
Opened 2020-06-26 17:31 UTC by nisarg73

Closes #1

2020-06-26 18:50 UTC, algomaster99 requested changes
@nisarg73 you will need to create a migration file too.

2020-06-26 19:23 UTC, nisarg73 commented
Yes. But that will be in faculty-biodata, where this AbstractProfile is inherited.

2020-06-26 20:53 UTC, algomaster99 commented
@nisarg73 Oh okay. I didn't notice if you have pushed the migration files in faculty_biodata.

2020-06-27 13:26 UTC, algomaster99 approved these changes

2020-06-27 13:36 UTC, merged